export const styles = {
  // ---- Layout ----
  appContainer: {
    display: "flex",
    height: "100vh",
    fontFamily: "'DM Sans', 'Segoe UI', system-ui, sans-serif",
    background: "#f8f7f4",
    color: "#1a1a2e",
  },

  // ---- Sidebar ----
  sidebar: {
    width: "230px",
    minWidth: "230px",
    background: "#1a1a2e",
    color: "#e0dfe4",
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid rgba(255,255,255,0.05)",
  },
  sidebarHeader: {
    padding: "24px 20px 16px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  logoIcon: {
    fontSize: "22px",
    color: "#a78bfa",
  },
  logoText: {
    fontSize: "18px",
    fontWeight: 700,
    letterSpacing: "-0.5px",
    color: "#fff",
  },
  logoSubtitle: {
    fontSize: "11px",
    color: "#6b7280",
    marginTop: "4px",
    letterSpacing: "1.5px",
    textTransform: "uppercase",
  },
  nav: {
    flex: 1,
    padding: "12px 8px",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "10px 12px",
    border: "none",
    borderRadius: "8px",
    background: "transparent",
    color: "#9ca3af",
    cursor: "pointer",
    fontSize: "13.5px",
    fontWeight: 500,
    transition: "all 0.15s ease",
    textAlign: "left",
    fontFamily: "inherit",
  },
  navItemActive: {
    background: "rgba(167, 139, 250, 0.12)",
    color: "#a78bfa",
  },
  navIcon: {
    display: "flex",
    alignItems: "center",
    width: "20px",
  },
  navLabel: {},
  navBadge: {
    marginLeft: "auto",
    background: "#a78bfa",
    color: "#fff",
    fontSize: "11px",
    fontWeight: 700,
    padding: "1px 7px",
    borderRadius: "10px",
  },
  sidebarFooter: {
    padding: "16px 20px",
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
  dateDisplay: {
    fontSize: "11.5px",
    color: "#6b7280",
  },

  // ---- Main content ----
  mainContent: {
    flex: 1,
    overflow: "auto",
  },
  viewContainer: {
    maxWidth: "960px",
    margin: "0 auto",
    padding: "32px 40px",
  },
  viewHeader: {
    marginBottom: "28px",
  },
  viewTitle: {
    fontSize: "26px",
    fontWeight: 700,
    color: "#1a1a2e",
    letterSpacing: "-0.5px",
    margin: 0,
  },
  viewSubtitle: {
    fontSize: "13px",
    color: "#6b7280",
    marginTop: "4px",
  },

  // ---- Cards ----
  card: {
    background: "#fff",
    borderRadius: "10px",
    padding: "18px 20px",
    marginBottom: "14px",
    border: "1px solid #e8e7e3",
    boxShadow: "0 1px 3px rgba(0,0,0,0.03)",
  },
  cardTitle: {
    fontSize: "14px",
    fontWeight: 600,
    marginBottom: "10px",
    color: "#1a1a2e",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    margin: "0 0 10px 0",
  },

  // ---- Today grid ----
  todayGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 320px",
    gap: "20px",
    alignItems: "start",
  },
  todayJournal: {},
  todaySidebar: {},

  // ---- Journal textarea ----
  journalTextarea: {
    width: "100%",
    minHeight: "80px",
    border: "1px solid #e8e7e3",
    borderRadius: "6px",
    padding: "10px 12px",
    fontSize: "13.5px",
    fontFamily: "'JetBrains Mono', 'SF Mono', monospace",
    lineHeight: 1.6,
    resize: "vertical",
    outline: "none",
    background: "#fafaf8",
    color: "#1a1a2e",
    boxSizing: "border-box",
    transition: "border-color 0.15s",
  },

  // ---- Todos ----
  todoList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  todoItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    background: "#fff",
    borderRadius: "8px",
    border: "1px solid #e8e7e3",
    borderLeft: "3px solid",
    transition: "box-shadow 0.15s",
  },
  todoCheckbox: {
    width: "20px",
    height: "20px",
    borderRadius: "4px",
    border: "2px solid #d1d5db",
    background: "transparent",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    flexShrink: 0,
    transition: "all 0.15s",
  },
  todoMeta: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "3px",
  },
  todoDue: {
    fontSize: "11.5px",
    display: "flex",
    alignItems: "center",
    gap: "3px",
  },
  todoTag: {
    fontSize: "11px",
    background: "#f3f0ff",
    color: "#7c3aed",
    padding: "1px 7px",
    borderRadius: "4px",
    fontWeight: 500,
  },
  todoActions: {
    display: "flex",
    gap: "4px",
    opacity: 0.4,
  },
  miniTodo: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 0",
    borderBottom: "1px solid #f3f2ef",
  },
  miniTodoText: {
    fontSize: "13px",
    color: "#1a1a2e",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  priorityDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    flexShrink: 0,
  },

  // ---- Quick add ----
  quickAdd: {
    marginTop: "8px",
  },
  quickAddInput: {
    width: "100%",
    padding: "10px 14px",
    border: "1px dashed #d1d5db",
    borderRadius: "8px",
    background: "transparent",
    fontSize: "13px",
    outline: "none",
    color: "#1a1a2e",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },

  // ---- Filters ----
  filterBar: {
    display: "flex",
    gap: "4px",
    marginTop: "16px",
  },
  filterBtn: {
    padding: "6px 14px",
    border: "1px solid #e8e7e3",
    borderRadius: "6px",
    background: "#fff",
    fontSize: "12.5px",
    fontWeight: 500,
    color: "#6b7280",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  filterBtnActive: {
    background: "#1a1a2e",
    color: "#fff",
    borderColor: "#1a1a2e",
  },

  // ---- Forms ----
  formInput: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid #e8e7e3",
    borderRadius: "6px",
    fontSize: "13.5px",
    outline: "none",
    marginBottom: "8px",
    fontFamily: "inherit",
    color: "#1a1a2e",
    boxSizing: "border-box",
  },
  formSelect: {
    padding: "8px 12px",
    border: "1px solid #e8e7e3",
    borderRadius: "6px",
    fontSize: "13px",
    outline: "none",
    fontFamily: "inherit",
    color: "#1a1a2e",
    background: "#fff",
  },
  formRow: {
    display: "flex",
    gap: "8px",
    marginBottom: "8px",
    flexWrap: "wrap",
  },
  formActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    marginTop: "4px",
  },

  // ---- Buttons ----
  primaryBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 16px",
    background: "#7c3aed",
    color: "#fff",
    border: "none",
    borderRadius: "7px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "background 0.15s",
  },
  secondaryBtn: {
    padding: "8px 16px",
    background: "#fff",
    color: "#374151",
    border: "1px solid #e8e7e3",
    borderRadius: "7px",
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  iconBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    border: "none",
    borderRadius: "6px",
    background: "transparent",
    color: "#6b7280",
    cursor: "pointer",
    transition: "background 0.15s",
  },

  // ---- Weekly plan ----
  weeklyGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
    alignItems: "start",
  },
  weekDayLabel: {
    fontSize: "11.5px",
    fontWeight: 600,
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "4px",
  },
  ratingRow: {
    display: "flex",
    gap: "6px",
  },
  ratingBtn: {
    width: "36px",
    height: "36px",
    borderRadius: "6px",
    border: "none",
    fontSize: "16px",
    cursor: "pointer",
    transition: "all 0.15s",
  },

  // ---- Calendar ----
  calendarContainer: {
    display: "flex",
    gap: "24px",
  },
  calendarGrid: {
    flex: 1,
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: "2px",
    background: "#e8e7e3",
    borderRadius: "10px",
    overflow: "hidden",
    border: "1px solid #e8e7e3",
  },
  calDayHeader: {
    padding: "8px",
    textAlign: "center",
    fontSize: "11.5px",
    fontWeight: 600,
    color: "#6b7280",
    background: "#f3f2ef",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  calDay: {
    background: "#fafaf8",
    minHeight: "72px",
    padding: "6px 8px",
    position: "relative",
    cursor: "default",
  },
  calDayActive: {
    background: "#fff",
    cursor: "pointer",
    transition: "background 0.15s",
  },
  calDayToday: {
    background: "#f5f3ff",
  },
  calDaySelected: {
    background: "#ede9fe",
    boxShadow: "inset 0 0 0 2px #7c3aed",
  },
  calDayNum: {
    fontSize: "13px",
    fontWeight: 500,
    color: "#374151",
  },
  calDots: {
    display: "flex",
    gap: "3px",
    flexWrap: "wrap",
    marginTop: "4px",
  },
  calDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
  },
  calSidebar: {
    width: "260px",
    background: "#fff",
    borderRadius: "10px",
    padding: "18px 20px",
    border: "1px solid #e8e7e3",
    alignSelf: "start",
  },
  calNoteText: {
    fontSize: "12.5px",
    color: "#4b5563",
    margin: "4px 0",
    lineHeight: 1.5,
  },

  // ---- Projects ----
  projectGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "14px",
    alignItems: "start",
  },
  projectCard: {
    background: "#fff",
    borderRadius: "10px",
    padding: "18px 20px",
    border: "1px solid #e8e7e3",
    cursor: "pointer",
    transition: "box-shadow 0.15s",
  },
  projectHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "6px",
  },
  projectName: {
    fontSize: "15px",
    fontWeight: 600,
    margin: 0,
    color: "#1a1a2e",
  },
  projectDesc: {
    fontSize: "12.5px",
    color: "#6b7280",
    margin: "0 0 8px 0",
    lineHeight: 1.5,
  },
  projectDeadline: {
    fontSize: "12px",
    color: "#6b7280",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    marginBottom: "10px",
  },
  statusDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
  },
  progressContainer: {
    marginTop: "8px",
  },
  progressBar: {
    height: "4px",
    background: "#e8e7e3",
    borderRadius: "2px",
    overflow: "hidden",
    marginBottom: "4px",
  },
  progressFill: {
    height: "100%",
    background: "linear-gradient(90deg, #7c3aed, #a78bfa)",
    borderRadius: "2px",
    transition: "width 0.3s ease",
  },
  progressText: {
    fontSize: "11px",
    color: "#9ca3af",
  },
  projectExpanded: {
    marginTop: "14px",
    paddingTop: "14px",
    borderTop: "1px solid #e8e7e3",
  },

  // ---- Misc ----
  smallTitle: {
    fontSize: "11.5px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    color: "#6b7280",
    margin: "0 0 6px 0",
  },
  emptyState: {
    fontSize: "12.5px",
    color: "#9ca3af",
    padding: "8px 0",
    fontStyle: "italic",
  },
  emptyStateLarge: {
    fontSize: "14px",
    color: "#9ca3af",
    textAlign: "center",
    padding: "40px 20px",
    gridColumn: "1 / -1",
  },
};
